//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbCliente
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int Id { get; set; }
        public int OrigenCuentaId { get; set; }
        public int DestinoCuentaId { get; set; }
        public int Valor { get; set; }
        public int ClienteId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
    }
}
